---
language: node_js
node_js:
  - "lts/*"

sudo: false
dist: trusty

addons:
  chrome: stable

cache: yarn

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run build -- -prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
  local-dir: dist
  verbose: true
